(() => {
  "use strict";
  const W=600,H=400,clamp=(n,a,b)=>Math.max(a,Math.min(b,n));
  function base(kind,level){return{kind,level,score:0,lives:3,over:false,checkpoint:false,keys:{},last:0}}
  function create(kind,level=1){
    const w=base(kind,level);
    if(kind==="arcade-space")Object.assign(w,{x:300,bullets:[],rocks:[],spawn:0,shot:0,nextQuiz:5});
    if(kind==="arcade-racer"){const walls=new Set;for(let x=0;x<20;x++){walls.add(`${x},0`);walls.add(`${x},13`)}for(let y=0;y<14;y++){walls.add(`0,${y}`);walls.add(`19,${y}`)}[[3,2,3,10],[7,3,7,12],[11,1,11,9],[15,4,15,12]].forEach(([x,y1,,y2])=>{for(let y=y1;y<=y2;y++)if(y!==6&&y!==10)walls.add(`${x},${y}`)});const pellets=new Set;for(let y=1;y<13;y++)for(let x=1;x<19;x++)if(!walls.has(`${x},${y}`))pellets.add(`${x},${y}`);Object.assign(w,{walls,pellets,px:1,py:1,gx:18,gy:12,enemyClock:0,moveClock:0,collected:0,direction:null,wantedDirection:null,quizIn:22+Math.random()*6,activeTime:0,invulnerable:2})}
    if(kind==="arcade-balloons")Object.assign(w,{board:Array.from({length:18},()=>Array(10).fill(0)),piece:null,fall:0,lines:0,nextQuiz:1});
    if(kind==="arcade-tower"){const cars=[];for(let lane=1;lane<=6;lane++){for(let j=0;j<2;j++)cars.push({lane,x:(j*320+lane*83)%650,speed:(42+lane*8)*(.85+level*.08)*(lane%2?-1:1)})}Object.assign(w,{px:300,py:365,cars,goals:0,nextQuiz:1,cooldown:0,invulnerable:0})}
    return w;
  }
  function rectHit(a,b){return a.x<b.x+b.w&&a.x+a.w>b.x&&a.y<b.y+b.h&&a.y+a.h>b.y}
  function spaceUpdate(w,dt){const speed=220+w.level*18;if(w.keys.left)w.x-=speed*dt;if(w.keys.right)w.x+=speed*dt;w.x=clamp(w.x,18,582);w.shot-=dt;if(w.keys.action&&w.shot<=0){w.bullets.push({x:w.x,y:342});w.shot=.22}w.spawn-=dt;if(w.spawn<=0){w.rocks.push({x:20+Math.random()*560,y:-22,r:12+Math.random()*13,v:75+w.level*18+Math.random()*45});w.spawn=Math.max(.35,1.05-w.level*.12)}w.bullets.forEach(b=>b.y-=330*dt);w.rocks.forEach(r=>r.y+=r.v*dt);for(let i=w.rocks.length-1;i>=0;i--){const r=w.rocks[i];let hit=false;for(let j=w.bullets.length-1;j>=0;j--)if(Math.hypot(r.x-w.bullets[j].x,r.y-w.bullets[j].y)<r.r+5){w.bullets.splice(j,1);w.rocks.splice(i,1);w.score++;hit=true;break}if(hit)continue;if(r.y>370&&Math.abs(r.x-w.x)<r.r+17){w.rocks.splice(i,1);w.lives--;if(w.lives<=0)w.over=true}else if(r.y>430)w.rocks.splice(i,1)}w.bullets=w.bullets.filter(b=>b.y>-20);if(w.score>=w.nextQuiz){w.nextQuiz+=5;w.checkpoint=true}}
  const mazeDirections={left:[-1,0],right:[1,0],up:[0,-1],down:[0,1]};
  function mazeCanMove(w,direction){const d=mazeDirections[direction];return d&&!w.walls.has(`${w.px+d[0]},${w.py+d[1]}`)}
  function mazeMove(w,direction){const d=mazeDirections[direction];if(!d||!mazeCanMove(w,direction))return false;w.px+=d[0];w.py+=d[1];const key=`${w.px},${w.py}`;if(w.pellets.delete(key)){w.collected++;w.score++}if(w.px===w.gx&&w.py===w.gy)mazeHit(w);return true}
  function mazeHit(w){if(w.invulnerable>0)return;w.lives--;w.invulnerable=2;w.px=1;w.py=1;w.gx=18;w.gy=12;if(w.lives<=0)w.over=true}
  function mazeUpdate(w,dt){w.invulnerable-=dt;w.enemyClock+=dt;if(w.direction||w.wantedDirection){w.activeTime+=dt;w.quizIn-=dt}w.moveClock+=dt;const step=Math.max(.105,.17-w.level*.012);if(w.moveClock>=step){w.moveClock%=step;if(mazeCanMove(w,w.wantedDirection))w.direction=w.wantedDirection;if(w.direction)mazeMove(w,w.direction)}if(w.quizIn<=0&&w.activeTime>=8&&w.collected>=3){w.quizIn=24+Math.random()*8;w.checkpoint=true;return}if(w.enemyClock>.7-Math.min(.2,w.level*.04)){w.enemyClock=0;const moves=[[1,0],[-1,0],[0,1],[0,-1]].filter(([dx,dy])=>!w.walls.has(`${w.gx+dx},${w.gy+dy}`)).sort((a,b)=>Math.abs(w.px-(w.gx+a[0]))+Math.abs(w.py-(w.gy+a[1]))-(Math.abs(w.px-(w.gx+b[0]))+Math.abs(w.py-(w.gy+b[1]))));if(moves[0]){w.gx+=moves[0][0];w.gy+=moves[0][1]}if(w.px===w.gx&&w.py===w.gy)mazeHit(w)}}
  const shapes=[[[1,1,1,1]],[[1,1],[1,1]],[[0,1,0],[1,1,1]],[[1,0,0],[1,1,1]],[[0,1,1],[1,1,0]]];
  function newPiece(w){const shape=shapes[Math.floor(Math.random()*shapes.length)].map(r=>r.slice());w.piece={shape,x:Math.floor((10-shape[0].length)/2),y:0};if(tetrisCollide(w,w.piece,0,0))w.over=true}
  function tetrisCollide(w,p,dx,dy,shape=p.shape){return shape.some((row,y)=>row.some((v,x)=>v&&(p.y+y+dy>=18||p.x+x+dx<0||p.x+x+dx>=10||p.y+y+dy>=0&&w.board[p.y+y+dy][p.x+x+dx])))}
  function tetrisLock(w){w.piece.shape.forEach((row,y)=>row.forEach((v,x)=>{if(v&&w.piece.y+y>=0)w.board[w.piece.y+y][w.piece.x+x]=1}));let cleared=0;w.board=w.board.filter(row=>{if(row.every(Boolean)){cleared++;return false}return true});while(w.board.length<18)w.board.unshift(Array(10).fill(0));if(cleared){w.lines+=cleared;w.score+=cleared*10;if(w.lines>=w.nextQuiz){w.nextQuiz=w.lines+1;w.checkpoint=true}}newPiece(w)}
  function tetrisDown(w){if(!w.piece)newPiece(w);if(!tetrisCollide(w,w.piece,0,1))w.piece.y++;else tetrisLock(w)}
  function tetrisUpdate(w,dt){if(!w.piece)newPiece(w);w.fall+=dt;if(w.fall>Math.max(.18,.72-w.level*.1)){w.fall=0;tetrisDown(w)}}
  function rotate(shape){return shape[0].map((_,i)=>shape.map(row=>row[i]).reverse())}
  function roadMove(w,dx,dy){if(w.cooldown>0)return;w.cooldown=.09;w.px=clamp(w.px+dx*50,25,575);w.py=clamp(w.py+dy*48,20,365);if(w.py<35){w.goals++;w.score+=10;w.px=300;w.py=365;if(w.goals>=w.nextQuiz){w.nextQuiz++;w.checkpoint=true}}}
  function roadHit(w){if(w.invulnerable>0)return;w.lives--;w.invulnerable=1;w.px=300;w.py=365;if(w.lives<=0)w.over=true}
  function roadUpdate(w,dt){w.cooldown-=dt;w.invulnerable-=dt;w.cars.forEach(c=>{c.x+=c.speed*dt;if(c.speed>0&&c.x>650)c.x=-80;if(c.speed<0&&c.x<-90)c.x=650;const cy=340-c.lane*48;if(rectHit({x:w.px-14,y:w.py-14,w:28,h:28},{x:c.x,y:cy-15,w:72,h:30}))roadHit(w)})}
  function update(w,dt){if(w.over||w.checkpoint)return;if(w.kind==="arcade-space")spaceUpdate(w,dt);else if(w.kind==="arcade-racer")mazeUpdate(w,dt);else if(w.kind==="arcade-balloons")tetrisUpdate(w,dt);else roadUpdate(w,dt)}
  function input(w,key,down=true){w.keys[key]=down;if(!down||w.over)return;if(w.kind==="arcade-racer"){if(mazeDirections[key])w.wantedDirection=key}else if(w.kind==="arcade-balloons"&&w.piece){if(key==="left"&&!tetrisCollide(w,w.piece,-1,0))w.piece.x--;if(key==="right"&&!tetrisCollide(w,w.piece,1,0))w.piece.x++;if(key==="down")tetrisDown(w);if(key==="up"){const s=rotate(w.piece.shape);if(!tetrisCollide(w,w.piece,0,0,s))w.piece.shape=s}if(key==="action"){while(!tetrisCollide(w,w.piece,0,1))w.piece.y++;tetrisLock(w)}}else if(w.kind==="arcade-tower"){if(key==="left")roadMove(w,-1,0);if(key==="right")roadMove(w,1,0);if(key==="up")roadMove(w,0,-1);if(key==="down")roadMove(w,0,1)}}
  function drawHud(ctx,w){ctx.fillStyle="#fff";ctx.font="700 15px sans-serif";ctx.fillText(`★ ${w.score}`,14,23);ctx.fillStyle="#ff9ca4";ctx.fillText(`♥ ${w.lives}`,530,23)}
  function drawSpace(ctx,w){ctx.fillStyle="#061522";ctx.fillRect(0,0,W,H);for(let i=0;i<45;i++){ctx.fillStyle=i%4?"#557386":"#ffe56b";ctx.fillRect((i*97)%W,(i*53+performance.now()/35)%H,2,2)}ctx.fillStyle="#c7f36c";ctx.beginPath();ctx.moveTo(w.x,345);ctx.lineTo(w.x-18,382);ctx.lineTo(w.x,374);ctx.lineTo(w.x+18,382);ctx.closePath();ctx.fill();ctx.fillStyle="#ffe56b";w.bullets.forEach(b=>ctx.fillRect(b.x-2,b.y,4,12));w.rocks.forEach(r=>{ctx.fillStyle="#a86f5b";ctx.beginPath();ctx.arc(r.x,r.y,r.r,0,Math.PI*2);ctx.fill()});drawHud(ctx,w)}
  function drawMaze(ctx,w){const cw=30,ch=28;ctx.fillStyle="#071522";ctx.fillRect(0,0,W,H);w.walls.forEach(k=>{const[x,y]=k.split(",").map(Number);ctx.fillStyle="#225574";ctx.fillRect(x*cw+2,y*ch+2,cw-4,ch-4)});ctx.fillStyle="#ffe56b";w.pellets.forEach(k=>{const[x,y]=k.split(",").map(Number);ctx.beginPath();ctx.arc(x*cw+15,y*ch+14,2.5,0,Math.PI*2);ctx.fill()});ctx.fillStyle="#c7f36c";ctx.beginPath();ctx.arc(w.px*cw+15,w.py*ch+14,10,.2,Math.PI*1.8);ctx.lineTo(w.px*cw+15,w.py*ch+14);ctx.fill();ctx.fillStyle="#ef6670";ctx.beginPath();ctx.arc(w.gx*cw+15,w.gy*ch+14,10,Math.PI,0);ctx.rect(w.gx*cw+5,w.gy*ch+14,20,10);ctx.fill();drawHud(ctx,w);ctx.fillStyle="#d9f0f5";ctx.font="700 13px sans-serif";ctx.fillText(`? ${Math.max(0,Math.ceil(w.quizIn))}s`,275,23)}
  function drawTetris(ctx,w){const cell=21,ox=195,oy=10;ctx.fillStyle="#071522";ctx.fillRect(0,0,W,H);ctx.fillStyle="#102a3b";ctx.fillRect(ox-4,oy-4,cell*10+8,cell*18+8);w.board.forEach((row,y)=>row.forEach((v,x)=>{if(v){ctx.fillStyle="#5ba7bf";ctx.fillRect(ox+x*cell+1,oy+y*cell+1,cell-2,cell-2)}}));if(w.piece)w.piece.shape.forEach((row,y)=>row.forEach((v,x)=>{if(v){ctx.fillStyle="#c7f36c";ctx.fillRect(ox+(w.piece.x+x)*cell+1,oy+(w.piece.y+y)*cell+1,cell-2,cell-2)}}));drawHud(ctx,w)}
  function drawRoad(ctx,w){ctx.fillStyle="#173b32";ctx.fillRect(0,0,W,H);ctx.fillStyle="#263746";ctx.fillRect(0,40,W,320);for(let lane=1;lane<=6;lane++){const y=340-lane*48;ctx.strokeStyle="#ffe56b55";ctx.setLineDash([18,18]);ctx.beginPath();ctx.moveTo(0,y+24);ctx.lineTo(W,y+24);ctx.stroke()}ctx.setLineDash([]);w.cars.forEach((c,i)=>{const y=340-c.lane*48;ctx.fillStyle=i%2?"#ef6670":"#5ba7bf";ctx.fillRect(c.x,y-15,72,30);ctx.fillStyle="#d9f0f5";ctx.fillRect(c.x+14,y-10,22,10)});ctx.fillStyle="#c7f36c";ctx.beginPath();ctx.arc(w.px,w.py,14,0,Math.PI*2);ctx.fill();ctx.fillStyle="#ffe56b";ctx.fillRect(0,18,W,8);drawHud(ctx,w)}
  function draw(w,canvas){const ctx=canvas.getContext("2d");if(w.kind==="arcade-space")drawSpace(ctx,w);else if(w.kind==="arcade-racer")drawMaze(ctx,w);else if(w.kind==="arcade-balloons")drawTetris(ctx,w);else drawRoad(ctx,w)}
  window.REAL_ARCADE={create,update,input,draw};
})();