(() => {
  "use strict";
  const languages={
    da:{chooseSubject:"Vælg emne",chooseLevel:"Vælg niveau",start:"Start spil",round:"Runde",score:"Point",lives:"Liv",streak:"Stime",read:"Læs opgaven",answer:"Vælg svaret",correct:"Flot!",wrong:"Det rigtige svar var",next:"Næste runde",finished:"Banen er gennemført!",again:"Spil igen",moveLeft:"Bevæg til venstre",moveRight:"Bevæg til højre",moveUp:"Bevæg op",moveDown:"Bevæg ned",fire:"Skyd",drop:"Slip blokken",subjects:{arithmetic:"Hovedregning",fractions:"Brøker",percent:"Procent og decimaler",geometry:"Geometri og måling"},levels:["Tryg start","Godt på vej","Udfordring","Ekspert"]},
    en:{chooseSubject:"Choose a subject",chooseLevel:"Choose a level",start:"Start game",round:"Round",score:"Score",lives:"Lives",streak:"Streak",read:"Read the question",answer:"Choose the answer",correct:"Great!",wrong:"The correct answer was",next:"Next round",finished:"Course complete!",again:"Play again",moveLeft:"Move left",moveRight:"Move right",moveUp:"Move up",moveDown:"Move down",fire:"Fire",drop:"Drop block",subjects:{arithmetic:"Mental arithmetic",fractions:"Fractions",percent:"Percentages and decimals",geometry:"Geometry and measurement"},levels:["Gentle start","Getting there","Challenge","Expert"]},
    fr:{chooseSubject:"Choisis un thème",chooseLevel:"Choisis un niveau",start:"Commencer",round:"Manche",score:"Score",lives:"Vies",streak:"Série",read:"Lis la question",answer:"Choisis la réponse",correct:"Bravo !",wrong:"La bonne réponse était",next:"Manche suivante",finished:"Parcours terminé !",again:"Rejouer",moveLeft:"Aller à gauche",moveRight:"Aller à droite",moveUp:"Aller en haut",moveDown:"Aller en bas",fire:"Tirer",drop:"Lâcher le bloc",subjects:{arithmetic:"Calcul mental",fractions:"Fractions",percent:"Pourcentages et décimaux",geometry:"Géométrie et mesures"},levels:["Départ tranquille","En progrès","Défi","Expert"]},
    es:{chooseSubject:"Elige un tema",chooseLevel:"Elige un nivel",start:"Empezar",round:"Ronda",score:"Puntos",lives:"Vidas",streak:"Racha",read:"Lee la pregunta",answer:"Elige la respuesta",correct:"¡Muy bien!",wrong:"La respuesta correcta era",next:"Siguiente ronda",finished:"¡Recorrido completado!",again:"Jugar otra vez",moveLeft:"Mover a la izquierda",moveRight:"Mover a la derecha",moveUp:"Mover arriba",moveDown:"Mover abajo",fire:"Disparar",drop:"Soltar bloque",subjects:{arithmetic:"Cálculo mental",fractions:"Fracciones",percent:"Porcentajes y decimales",geometry:"Geometría y medida"},levels:["Inicio tranquilo","En camino","Desafío","Experto"]},
    uk:{chooseSubject:"Обери тему",chooseLevel:"Обери рівень",start:"Почати",round:"Раунд",score:"Бали",lives:"Життя",streak:"Серія",read:"Прочитай завдання",answer:"Обери відповідь",correct:"Чудово!",wrong:"Правильна відповідь",next:"Наступний раунд",finished:"Маршрут завершено!",again:"Грати ще",moveLeft:"Рух ліворуч",moveRight:"Рух праворуч",moveUp:"Рух угору",moveDown:"Рух униз",fire:"Стріляти",drop:"Скинути блок",subjects:{arithmetic:"Усний рахунок",fractions:"Дроби",percent:"Відсотки й десяткові дроби",geometry:"Геометрія та вимірювання"},levels:["Легкий старт","На шляху","Виклик","Експерт"]},
    ru:{chooseSubject:"Выбери тему",chooseLevel:"Выбери уровень",start:"Начать",round:"Раунд",score:"Очки",lives:"Жизни",streak:"Серия",read:"Прочитай задачу",answer:"Выбери ответ",correct:"Отлично!",wrong:"Правильный ответ",next:"Следующий раунд",finished:"Маршрут пройден!",again:"Играть ещё",moveLeft:"Двигаться влево",moveRight:"Двигаться вправо",moveUp:"Двигаться вверх",moveDown:"Двигаться вниз",fire:"Стрелять",drop:"Сбросить блок",subjects:{arithmetic:"Устный счёт",fractions:"Дроби",percent:"Проценты и десятичные дроби",geometry:"Геометрия и измерения"},levels:["Лёгкий старт","На пути","Испытание","Эксперт"]},
    sq:{chooseSubject:"Zgjidh temën",chooseLevel:"Zgjidh nivelin",start:"Fillo lojën",round:"Raundi",score:"Pikë",lives:"Jetë",streak:"Seri",read:"Lexo pyetjen",answer:"Zgjidh përgjigjen",correct:"Shkëlqyeshëm!",wrong:"Përgjigjja e saktë ishte",next:"Raundi tjetër",finished:"Rruga u përfundua!",again:"Luaj përsëri",moveLeft:"Lëviz majtas",moveRight:"Lëviz djathtas",moveUp:"Lëviz lart",moveDown:"Lëviz poshtë",fire:"Gjuaj",drop:"Lësho bllokun",subjects:{arithmetic:"Llogaritje me mend",fractions:"Thyesat",percent:"Përqindjet dhe numrat dhjetorë",geometry:"Gjeometria dhe matja"},levels:["Fillim i lehtë","Në rrugë të mbarë","Sfidë","Ekspert"]}
  };
  const subjectInfo={arithmetic:{icon:"➕",examples:["8 + 7","6 × 4","125 − 48","18 ÷ 3 + 7"]},fractions:{icon:"½",examples:["1/4 + 2/4","2/3 = ?/12","1/2 + 1/3","3/4 ÷ 1/2"]},percent:{icon:"%",examples:["50% × 20","25% × 80","15% × 240","200 − 20%"]},geometry:{icon:"📐",examples:["P(▭ 3 × 5)","A(▭ 6 × 4)","2.5 m = ? cm","V(▣ 3 × 4 × 5)"]}};
  const gameCopy={
    "arcade-space":{icon:"🚀",da:["Asteroideforsvaret","Styr rumskibet, skyd asteroider og undgå sammenstød."],en:["Asteroid Defender","Steer the ship, shoot asteroids and avoid collisions."],fr:["Défense anti-astéroïdes","Pilote le vaisseau, détruis les astéroïdes et évite les collisions."],es:["Defensor de asteroides","Pilota la nave, dispara a los asteroides y evita choques."],uk:["Захисник від астероїдів","Керуй кораблем, стріляй в астероїди та уникай зіткнень."],ru:["Защитник от астероидов","Управляй кораблём, стреляй в астероиды и избегай столкновений."],sq:["Mbrojtësi nga asteroidët","Drejto anijen, godit asteroidët dhe shmang përplasjet."]},
    "arcade-racer":{icon:"🟡",da:["Labyrintslugeren","Spis prikkerne i labyrinten og hold dig væk fra spøgelset."],en:["Maze Muncher","Eat the maze dots and stay away from the ghost."],fr:["Croque-labyrinthe","Mange les points du labyrinthe et évite le fantôme."],es:["Come-laberintos","Come los puntos del laberinto y evita al fantasma."],uk:["Пожирач лабіринту","Збирай крапки в лабіринті та уникай привида."],ru:["Пожиратель лабиринта","Собирай точки в лабиринте и избегай призрака."],sq:["Gllabëruesi i labirintit","Mblidh pikat në labirint dhe shmang fantazmën."]},
    "arcade-balloons":{icon:"🧱",da:["Blokfald","Flyt og drej faldende blokke, og ryd hele linjer."],en:["Block Drop","Move and rotate falling blocks to clear complete lines."],fr:["Chute de blocs","Déplace et tourne les blocs pour compléter des lignes."],es:["Caída de bloques","Mueve y gira los bloques para completar líneas."],uk:["Падіння блоків","Рухай і обертай блоки, щоб складати повні лінії."],ru:["Падение блоков","Двигай и вращай блоки, чтобы собирать полные линии."],sq:["Rënia e blloqeve","Lëviz dhe rrotullo blloqet për të plotësuar rreshta."]},
    "arcade-tower":{icon:"🐸",da:["Trafikspringeren","Kryds de travle veje, undgå bilerne og nå sikkerhedszonen."],en:["Road Hopper","Cross the busy roads, dodge the cars and reach the safe zone."],fr:["Saute-route","Traverse les routes, évite les voitures et rejoins la zone sûre."],es:["Saltador de carretera","Cruza las carreteras, esquiva los coches y llega a salvo."],uk:["Дорожній стрибун","Перетинай дороги, уникай машин і дістанься безпечної зони."],ru:["Дорожный прыгун","Переходи дороги, избегай машин и доберись до безопасной зоны."],sq:["Kërcyesi i rrugës","Kalo rrugët, shmang makinat dhe arrij zonën e sigurt."]}
  };
  const slots={};
  const rand=(a,b)=>a+Math.floor(Math.random()*(b-a+1));
  const gcd=(a,b)=>{while(b)[a,b]=[b,a%b];return Math.abs(a)};
  const frac=(n,d)=>{const g=gcd(n,d);n/=g;d/=g;return d===1?String(n):`${n}/${d}`};
  const shuffle=a=>{for(let i=a.length-1;i;i--){const j=rand(0,i);[a[i],a[j]]=[a[j],a[i]]}return a};
  function choices(answer,candidates,key){const set=new Set(candidates.map(String).filter(x=>x!==String(answer)&&x!=="0"&&!x.startsWith("-")));const n=Number(answer);for(let step=1;set.size<3;step++)set.add(String(Number.isFinite(n)?n+step:step));const wrong=shuffle([...set]).slice(0,3);if(!slots[key]?.length)slots[key]=shuffle([0,1,2,3]);wrong.splice(slots[key].shift(),0,String(answer));return wrong}
  function arithmetic(level){let a,b,prompt,answer;if(level===1){a=rand(2,20);b=rand(1,Math.min(12,a));const add=Math.random()<.55;prompt=`${a} ${add?"+":"−"} ${b} = ?`;answer=add?a+b:a-b}else if(level===2){b=rand(2,10);answer=rand(2,10);const multiply=Math.random()<.65;a=b*answer;prompt=multiply?`${b} × ${answer} = ?`:`${a} ÷ ${b} = ?`;answer=multiply?a:answer}else if(level===3){a=rand(20,150);b=rand(11,80);const op=rand(0,2);if(op===0){prompt=`${a} + ${b} = ?`;answer=a+b}else if(op===1){if(b>a)[a,b]=[b,a];prompt=`${a} − ${b} = ?`;answer=a-b}else{b=rand(3,12);a=rand(11,30);prompt=`${a} × ${b} = ?`;answer=a*b}}else{a=rand(12,60);b=rand(3,12);const c=rand(2,15);prompt=`${a} − ${b} × ${c} = ?`;answer=a-b*c;if(answer<=0){prompt=`${a} + ${b} × ${c} = ?`;answer=a+b*c}}return{prompt,answer:String(answer),options:choices(answer,[answer+1,answer-1,answer+2,answer*2],`a${level}`)}}
  function fractions(level){const ds=level===1?[2,3,4,5]:level===2?[2,3,4,5,6,8]:[2,3,4,5,6,8,10,12],d=ds[rand(0,ds.length-1)],n=rand(1,d-1);let prompt,answer;if(level===1){const b=rand(1,d-n);prompt=`${n}/${d} + ${b}/${d} = ?`;answer=frac(n+b,d)}else if(level===2){const f=rand(2,4);prompt=`${n}/${d} = ?/${d*f}`;answer=String(n*f)}else if(level===3){const d2=ds[rand(0,ds.length-1)],b=rand(1,d2-1);prompt=`${n}/${d} + ${b}/${d2} = ?`;answer=frac(n*d2+b*d,d*d2)}else{const d2=ds[rand(0,ds.length-1)],b=rand(1,d2-1);prompt=`${n}/${d} ÷ ${b}/${d2} = ?`;answer=frac(n*d2,d*b)}let candidates;if(answer.includes("/")){const [x,y]=answer.split("/").map(Number);candidates=[frac(x+1,y),frac(Math.max(1,x-1),y),frac(x,y+1),frac(y,x)]}else{const x=Number(answer);candidates=[x+1,Math.max(1,x-1),x+2,x*2]}return{prompt,answer,options:choices(answer,candidates,`f${level}`)}}
  function percent(level){let pct,total,prompt,answer;if(level===1){pct=[10,25,50][rand(0,2)];total=[20,40,60,80,100][rand(0,4)];prompt=`${pct}% × ${total} = ?`;answer=pct*total/100}else if(level===2){pct=[10,20,25,40,50,75][rand(0,5)];total=rand(2,12)*20;prompt=`${pct}% × ${total} = ?`;answer=pct*total/100}else if(level===3){pct=[15,20,30,35,60][rand(0,4)];total=rand(4,20)*20;prompt=`${pct}% × ${total} = ?`;answer=pct*total/100}else{pct=[10,15,20,25][rand(0,3)];total=rand(5,30)*20;const discount=total*pct/100;prompt=`${total} − ${pct}% = ?`;answer=total-discount}return{prompt,answer:String(answer),options:choices(answer,[answer+5,answer-5,total-answer,answer+10],`p${level}`)}}
  function geometry(level){let a,b,c,prompt,answer;if(level===1){a=rand(2,10);b=rand(2,10);prompt=`P(▭ ${a} × ${b}) = ?`;answer=2*(a+b)}else if(level===2){a=rand(3,15);b=rand(3,12);prompt=`A(▭ ${a} × ${b}) = ?`;answer=a*b}else if(level===3){a=rand(2,12);prompt=`${a} m = ? cm`;answer=a*100}else{a=rand(2,10);b=rand(2,8);c=rand(2,6);prompt=`V(▣ ${a} × ${b} × ${c}) = ?`;answer=a*b*c}return{prompt,answer:String(answer),options:choices(answer,[answer+2,answer-2,answer+10,Math.max(1,Math.round(answer/2))],`g${level}`)}}
  function question(subject,level){return({arithmetic,fractions,percent,geometry}[subject]||arithmetic)(level)}
  const activities=[];
  Object.entries(gameCopy).forEach(([id,game])=>{const content={};Object.keys(languages).forEach(lang=>{const pair=game[lang]||game.en;content[lang]={title:pair[0],description:pair[1],skills:Object.values(languages[lang].subjects),finish:languages[lang].finished,parts:[]}});activities.push({id:`game-${id}`,type:"game",grade:6,grades:[4,5,6],icon:game.icon,minutes:12,gameKind:id,noTeacherGuide:true,parts:[],content})});
  window.PORTAL_CONTENT.activities.push(...activities);
  window.ARCADE_BANK={languages,subjectInfo,gameCopy,question,shuffle};
})();
